---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-adp-operatorgroup
  namespace: openshift-adp
spec:
  upgradeStrategy: Default
  targetNamespaces:
        - openshift-adp