apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  labels:
    app.kubernetes.io/component: velero
  name: velero
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  backupImages: false
  configuration:
    nodeAgent:
      enable: false
      uploaderType: kopia
    velero:
      defaultPlugins:
      - openshift
      - aws
      - kubevirt
      disableFsBackup: false
      noDefaultBackupLocation: true
  logFormat: text